### Health check
GET http://localhost:5002/

### Create a new participant
POST http://localhost:5002/participants
Content-Type: application/json

{
    "Name": "john doe",
    "SSN": "",
    "HomePhone": "4543-555-5555",
    "MobilePhone": "666-555-5555"
}

### Get participant by ID
GET http://localhost:5002/participants/events/1001

### Deactivate participant
DELETE http://localhost:5002/participants/1005