### Health check
GET http://localhost:5002/

### Create a new participant
POST http://localhost:5002/participants
Content-Type: application/json

{
    "Name": "eefse Doe"
}

### Get participant by ID
GET http://localhost:5002/participants/1001