### Health check
GET http://localhost:5002/

### Create a new participant
POST http://localhost:5002/participants
Content-Type: application/json

{
    "Name": "john doe",
    "SSN": "",
    "HomePhone": "111-555-5555",
    "MobilePhone": "111-555-5555",
    "Email": "111@test.com",
    "Address": {
        "Address1": "111 main st",
        "Address2": "",
        "City": "New York",
        "State": "NY",
        "Zip": "10001",
        "Country": "USA"
    }
}

### Get participant by ID
GET http://localhost:5002/participants/events/1001

### Get participant by ID
GET http://localhost:5002/participants/1001

### Deactivate participant
DELETE http://localhost:5002/participants/1005